/*
 * File: app/view/ui/BasePage.js
 * Date: Thu Jan 26 2012 10:25:23 GMT+0100 (CET)
 *
 * This file was generated by Ext Designer version 1.2.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.define('istsos.view.ui.BasePage', {
    extend: 'Ext.panel.Panel',

    border: 0,
    height: 250,
    width: 400,
    layout: {
        type: 'border'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    height: 40,
                    bodyBorder: true,
                    bodyCls: 'centerTitle',
                    bodyPadding: '8px',
                    region: 'north'
                },
                {
                    xtype: 'panel',
                    height: 40,
                    styleHtmlContent: true,
                    bodyBorder: true,
                    bodyCls: 'centerBody',
                    bodyPadding: '8 8 8 16',
                    region: 'center'
                },
                {
                    xtype: 'panel',
                    border: 0,
                    height: 50,
                    bodyPadding: '8px',
                    region: 'south'
                }
            ]
        });

        me.callParent(arguments);
    }
});