/*
 * File: app/view/ui/MainPanel.js
 * Date: Thu Jan 26 2012 10:25:23 GMT+0100 (CET)
 *
 * This file was generated by Ext Designer version 1.2.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.define('istsos.view.ui.MainPanel', {
    extend: 'Ext.container.Viewport',

    id: 'mainPanel',
    itemId: '',
    layout: {
        type: 'border'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    border: 0,
                    id: 'mainCenter',
                    layout: {
                        type: 'fit'
                    },
                    bodyPadding: '8px',
                    title: '',
                    region: 'center'
                },
                {
                    xtype: 'panel',
                    border: 0,
                    height: 70,
                    html: '<div class=\'mainHeaderTitle\'>GeoShield manager</div>\n<div class=\'mainHeaderSubtitle\'> &gt; Control Panel for GeoShield</div>',
                    id: 'mainHead',
                    bodyCls: 'mainHeader',
                    bodyPadding: '15 0 0 8',
                    title: '',
                    region: 'north'
                },
                {
                    xtype: 'panel',
                    border: 0,
                    height: 25,
                    html: 'Open Source Software by Institute of Earth Science - SUPSI',
                    id: 'mainFoot',
                    bodyCls: 'mainFooter',
                    bodyPadding: 8,
                    title: '',
                    region: 'south'
                },
                {
                    xtype: 'component',
                    id: 'mainMenu',
                    padding: '10px',
                    style: 'background: #fff;',
                    styleHtmlContent: true,
                    width: 150,
                    region: 'west'
                }
            ]
        });

        me.callParent(arguments);
    }
});