/*
 * File: app/view/ui/FormContactInfo.js
 * Date: Thu Jan 26 2012 10:25:23 GMT+0100 (CET)
 *
 * This file was generated by Ext Designer version 1.2.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.define('istsos.view.ui.FormContactInfo', {
    extend: 'Ext.form.Panel',

    border: 0,
    bodyPadding: 10,
    bodyStyle: 'centerBody',
    title: '',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'textfield',
                    fieldLabel: 'Contact',
                    anchor: '100%'
                },
                {
                    xtype: 'textfield',
                    fieldLabel: 'Organization',
                    anchor: '100%'
                },
                {
                    xtype: 'textfield',
                    fieldLabel: 'Position',
                    anchor: '100%'
                },
                {
                    xtype: 'textfield',
                    fieldLabel: 'Address type',
                    anchor: '100%'
                },
                {
                    xtype: 'textfield',
                    fieldLabel: 'Address',
                    anchor: '100%'
                },
                {
                    xtype: 'textfield',
                    fieldLabel: 'City',
                    anchor: '100%'
                },
                {
                    xtype: 'textfield',
                    fieldLabel: 'State',
                    anchor: '100%'
                },
                {
                    xtype: 'textfield',
                    fieldLabel: 'ZIP code',
                    anchor: '100%'
                },
                {
                    xtype: 'textfield',
                    fieldLabel: 'Coutry',
                    anchor: '100%'
                },
                {
                    xtype: 'textfield',
                    fieldLabel: 'Telephone',
                    anchor: '100%'
                },
                {
                    xtype: 'textfield',
                    fieldLabel: 'Fax',
                    anchor: '100%'
                },
                {
                    xtype: 'textfield',
                    fieldLabel: 'Email',
                    anchor: '100%'
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    ui: 'footer',
                    width: 30,
                    dock: 'bottom',
                    layout: {
                        pack: 'end',
                        type: 'hbox'
                    },
                    items: [
                        {
                            xtype: 'button',
                            text: 'Cancel'
                        },
                        {
                            xtype: 'button',
                            cls: 'istsos-btn',
                            text: 'Submit'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }
});