/*
 * File: app/view/FormAbout.js
 * Date: Thu Jan 26 2012 10:22:30 GMT+0100 (CET)
 *
 * This file was generated by Ext Designer version 1.2.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

Ext.define('istsos.view.FormAbout', {
    extend: 'istsos.view.ui.FormAbout',

    initComponent: function() {
        var me = this;
        me.callParent(arguments);
    }
});