/*
 * File: app/view/FormContactInfo.js
 * Date: Tue Dec 27 2011 16:41:25 GMT+0100 (CET)
 *
 * This file was generated by Ext Designer version 1.2.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

Ext.define('istsos.view.FormContactInfo', {
    extend: 'istsos.view.ui.FormContactInfo',

    initComponent: function() {
        var me = this;
        me.callParent(arguments);
    }
});