/*
 * File: app/view/FormConfig.js
 * Date: Wed Dec 28 2011 16:04:35 GMT+0100 (CET)
 *
 * This file was generated by Ext Designer version 1.2.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

Ext.define('istsos.view.FormConfig', {
    extend: 'istsos.view.ui.FormConfig',

    initComponent: function() {
        var me = this;
        me.callParent(arguments);
    }
});